name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2' # Adjust based on your Xcode version

    - name: Build and Run Tests
      run: |
        xcodebuild clean test \
          -scheme ToDoApp \
          -destination 'platform=macOS' \
          -enableCodeCoverage YES
